query MaintenanceRequests {
  maintenanceRequests {
    maintenanceRequests {
      ...MaintenanceRequestFragment
    }
    metrics {
      openCount
      averageResolutionTime
      urgentCount
    }
  }
}